var nav = document.createElement('nav');
nav.classList.add("p-4", "navbar", "bg-warning", "bg-gradient", "text-white", "navbar-expand-lg", "justify-content-sm-between"); //"container-fluid"
var boxBrand = document.createElement('div');
nav.appendChild(boxBrand);
var homeLink = document.createElement('a');
homeLink.classList.add("btn-link", "text-white", "text-decoration-none");
homeLink.setAttribute('href', "./index.html");
homeLink.setAttribute('role', "button");
boxBrand.appendChild(homeLink);
var pageTitle = document.createElement('h1');
pageTitle.appendChild(document.createTextNode("ToDoList"));
homeLink.appendChild(pageTitle);
var boxNav = document.createElement('div');
boxNav.classList.add("d-lg-block", "d-none", "d-sm-block", "d-md-block", "d-lg-block", "d-md-none", "d-sm-none");
nav.appendChild(boxNav);
var listNav = document.createElement('ul');
listNav.classList.add("nav");
var liNav1 = document.createElement('li');
listNav.appendChild(liNav1);
var liNav2 = document.createElement('li');
listNav.appendChild(liNav2);
var liNav3 = document.createElement('li');
listNav.appendChild(liNav3);
boxNav.appendChild(listNav);
var addCategories = document.createElement('a');
addCategories.setAttribute("role", "button");
addCategories.classList.add("btn", "btn-success");
addCategories.setAttribute('href', "./categories.html");
addCategories.appendChild(document.createTextNode('+Categoria'));
liNav1.appendChild(addCategories);
var addUsers = document.createElement('a');
addUsers.setAttribute("role", "button");
addUsers.classList.add("btn", "btn-success");
addUsers.setAttribute('href', "./users.html");
addUsers.appendChild(document.createTextNode('+Usuarios '));
liNav2.appendChild(addUsers);
var addTasks = document.createElement('a');
addTasks.setAttribute("role", "button");
addTasks.classList.add("btn", "btn-success");
addTasks.setAttribute('href', "./reports.html");
addTasks.appendChild(document.createTextNode('+Tareas'));
liNav3.appendChild(addTasks);
header.appendChild(nav);
